import Foundation

/// Build-time configuration baked into the app.
///
/// These values are compiled into the binary and are not exposed to or
/// editable by the end user. Adjust them here before distributing a build.
enum AppConfig {
    /// WebSocket endpoint of the relay server (TLS via nginx).
    static let serverURL = "wss://unifi-protect-camera-popup-server.snackbits.dev/ws"

    /// Bearer token the app uses to authenticate the WebSocket connection.
    static let appToken = "fc4hx4g267g34gr3i4gtcjgx76gr347irc3i4tgi7gtc94710z43x1tt67cgf7jrhfxznngcsfjuzegbfa"

    /// Display version shown in the menu bar; incremented by `scripts/build-release.sh`.
    static let buildNumber = 5

    /// Build identifier, rewritten by `scripts/build-release.sh` on every release.
    /// Must match the server's `versionId`; otherwise the server rejects the
    /// connection and the app shows an "outdated version" warning.
    static let buildVersionId = "695ff1c8-cc51-475f-9612-923f71e59f3d"

    /// HTTPS endpoint serving the update manifest (the server's `version.json`).
    /// The app polls this to detect whether a newer build is available.
    static let updateManifestURL = "https://unifi-protect-camera-popup-server.snackbits.dev/version"

    /// Base64-encoded raw Ed25519 public key used to verify downloaded updates.
    /// Generated by `scripts/update-keygen.swift`; the matching private key
    /// signs each release in `scripts/build-release.sh`. Empty disables updates.
    static let updatePublicKey = "TJHrEMkQI4Orhkkm6deRQWi/M+bsYidmr6RnWn1dkfM="

    /// Base URL UniFi Protect posts webhooks to. The full path is
    /// `<webhookBaseURL>/<installationId>/<webhook-slug>`.
    static let webhookBaseURL = "http://159.69.76.60:3847/webhook"

    /// Placeholder used when displaying the webhook URL template.
    static let webhookSlugPlaceholder = "<WEBHOOK-SLUG>"

    static func webhookURL(installationId: String, slug: String = AppConfig.webhookSlugPlaceholder) -> String {
        let safeSlug = slug.isEmpty ? webhookSlugPlaceholder : slug
        return "\(webhookBaseURL)/\(installationId)/\(safeSlug)"
    }
}
